# Generated by Django 3.2.21 on 2023-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('descripton', models.TextField()),
                ('status', models.CharField(choices=[('Done', 'Done'), ('In progress', 'In progress'), ('Not Done', 'Not Done')], max_length=50)),
            ],
        ),
    ]
