# Generated by Django 3.2.21 on 2023-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In progress', 'In progress'), ('Not Done', 'Not Done'), ('muna', 'muna')], max_length=50),
        ),
    ]
