# Generated by Django 5.0.4 on 2024-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231002_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('गरियो', 'गरियो'), ('गर्दै', 'गर्दै'), ('गरेको छैन', 'गरेको छैन')], max_length=50),
        ),
    ]
